#!/bin/bash
#SBATCH --job-name=bc
#SBATCH --ntasks=1
#SBATCH --gres=gpu:rtx8000:1
#SBATCH --time=20:00:00
#SBATCH --mem=16Gb

module load anaconda/3
conda activate csd
# wandb login 3323892d9a4991ee28c9d175976b0b8a921dcf37
bash bg_calc.sh
