#!/bin/bash
#SBATCH --job-name=crystal-graph-coord
#SBATCH --output=graph_out_coord.txt
#SBATCH --error=graph_err_coord.txt
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=10:00:00
#SBATCH --mem=32Gb

module load anaconda/3
conda activate csd
wandb login 3323892d9a4991ee28c9d175976b0b8a921dcf37
python3 /home/mila/p/prashant.govindarajan/scratch/crystal_design_project/crystal-design/crystal_design/main.py -p /home/mila/p/prashant.govindarajan/scratch/crystal_design_project/crystal-design/crystal_design/config/crystal/rainbow_graph.yml
