#!/bin/bash
#SBATCH --job-name=bc-mg
#SBATCH --ntasks=16
#SBATCH --gres=gpu:rtx8000:1
#SBATCH --time=48:00:00
#SBATCH --mem=64Gb
#SBATCH --output=output/experiment-%A.%a.err
#SBATCH --error=error/experiment-%A.%a.out

module load anaconda/3
conda activate csd
wandb login 3323892d9a4991ee28c9d175976b0b8a921dcf37
python bc_trainer.py --exp_num 0 --num_traj_per_crystal 5 --agent EGNNAgentBC --batch_size 2048 --learning_rate 5e-4 --epochs 2000 --graph_type mg --agg mean
