#!/bin/bash
#SBATCH --job-name=bc-nm
#SBATCH --ntasks=16
#SBATCH --gres=gpu:rtx8000:1
#SBATCH --time=48:00:00
#SBATCH --mem=32Gb
#SBATCH --output=output/experiment-%A.%a.out
#SBATCH --error=error/experiment-%A.%a.err
module load anaconda/3
conda activate csd
wandb login <API_KEY>

python cql_trainer.py --alpha1 $1 --alpha2 $2 --beta $3 --cql_min_q_weight $4 --project 'CQL-NONMETALS-MOREDATA' --group $5 --si_bg 1.12 --data_path '/home/mila/p/prashant.govindarajan/scratch/crystal_design_project/crystal-design/crystal_design/offline/trajectories/train_mp_nonmetals_x5.pt'

