alpha1: 0.0
alpha2: 10.0
alpha_multiplier: 10.0
backup_entropy: false
batch_size: 1024
bc_steps: 0
beta: 3.0
buffer_size: 2000000
checkpoints_path: /home/mila/p/prashant.govindarajan/scratch/crystal_design_project/crystal-design/crystal_design/cql_models/models_1/Run1-crystal-5ba270b5
cql_clip_diff_max: .inf
cql_clip_diff_min: -.inf
cql_importance_sample: true
cql_lagrange: false
cql_max_target_backup: false
cql_min_q_weight: 1.0
cql_n_actions: 10
cql_target_action_gap: -1.0
cql_temp: 1.0
data_path: /home/mila/p/prashant.govindarajan/scratch/crystal_design_project/crystal-design/crystal_design/offline/trajectories/train_mp_nonmetals_x5.pt
device: cuda
discount: 0.99
env: crystal
eval_freq: 10
group: 112megnet-MG-w1-0-10-3
load_model: ''
max_timesteps: 10000000
n_episodes: 10
name: Run1-crystal-5ba270b5
normalize: true
normalize_reward: false
orthogonal_init: true
policy_lr: 3.0e-05
project: CQL-NONMETALS-MOREDATA
qf_lr: 0.0003
seed: 0
si_bg: 1.12
soft_target_update_rate: 0.005
target_update_period: 1
use_automatic_entropy_tuning: true
